// lib/housing/neighborhood.ts
//
// Neighborhood-trajectory scoring from free Census ACS data — the "is this ZIP appreciating or declining"
// read that PropStream charges for. Built from a committed snapshot (lib/housing/data/zip-acs.json,
// generated by `npm run data:acs`) so scoring stays pure/synchronous with no call-time I/O, like the
// $/sqft and rent snapshots. Two ACS 5-year vintages give income + population GROWTH; falling vacancy is a
// bonus. Returns null for a ZIP we have no data on — never invents a trajectory. Every number is real
// public data; the composite score is a transparent, labeled blend, not a black box.

import acs from "./data/zip-acs.json";

export interface AcsZip {
  income?: number; // latest median household income
  pop?: number; // latest population
  vacancyPct?: number; // latest residential vacancy %
  incomeGrowthPct?: number; // vs the prior vintage
  popGrowthPct?: number;
  vacancyDeltaPct?: number; // change in vacancy (negative = improving)
}

const BY_ZIP: Record<string, AcsZip> =
  (acs as { byZip?: Record<string, AcsZip> }).byZip || {};

export const ACS_UPDATED: string = (acs as { updated?: string }).updated || "";

export type Trajectory = "rising" | "stable" | "declining";

export interface NeighborhoodScore {
  score: number; // 0–100 composite
  trajectory: Trajectory;
  label: string; // human, e.g. "Rising — incomes +9%, population +3%"
  income: number | null;
  incomeGrowthPct: number | null;
  popGrowthPct: number | null;
  vacancyPct: number | null;
}

const clamp = (n: number, lo: number, hi: number) =>
  Math.max(lo, Math.min(hi, n));

/**
 * Neighborhood trajectory for a ZIP. Composite 0–100 from income growth (the strongest appreciation
 * signal), population growth, and vacancy direction — each mapped to a bounded sub-score and blended.
 * Null when the ZIP isn't in the ACS snapshot (so callers show nothing rather than a fabricated read).
 */
export function neighborhoodScore(
  zip?: string | null,
): NeighborhoodScore | null {
  const z = zip ? String(zip).trim().slice(0, 5) : "";
  const d = BY_ZIP[z];
  if (!d) return null;

  const ig = d.incomeGrowthPct ?? null;
  const pg = d.popGrowthPct ?? null;
  const vac = d.vacancyPct ?? null;
  const vd = d.vacancyDeltaPct ?? null;

  // Sub-scores, each 0–100, centered at 50 (flat). Income growth weighted most.
  const incomeSub = ig == null ? 50 : clamp(50 + ig * 3, 0, 100); // +17% → 100
  const popSub = pg == null ? 50 : clamp(50 + pg * 5, 0, 100); // +10% → 100
  const vacSub =
    vd == null
      ? vac == null
        ? 50
        : clamp(70 - vac * 2, 0, 100) // static: low vacancy = better
      : clamp(50 - vd * 6, 0, 100); // improving (−) vacancy = better

  const score = Math.round(incomeSub * 0.5 + popSub * 0.3 + vacSub * 0.2);
  const trajectory: Trajectory =
    score >= 62 ? "rising" : score <= 42 ? "declining" : "stable";

  const parts: string[] = [];
  if (ig != null) parts.push(`incomes ${ig >= 0 ? "+" : ""}${ig}%`);
  if (pg != null) parts.push(`population ${pg >= 0 ? "+" : ""}${pg}%`);
  const cap = trajectory[0].toUpperCase() + trajectory.slice(1);
  const label = parts.length ? `${cap} — ${parts.join(", ")}` : cap;

  return {
    score,
    trajectory,
    label,
    income: d.income ?? null,
    incomeGrowthPct: ig,
    popGrowthPct: pg,
    vacancyPct: vac,
  };
}
