// lib/housing/neighborhood.ts
//
// Neighborhood-trajectory scoring from free Census ACS data — the "is this ZIP appreciating or declining"
// read that PropStream charges for. Built from a committed snapshot (lib/housing/data/zip-acs.json,
// generated by `npm run data:acs`) so scoring stays pure/synchronous with no call-time I/O, like the
// $/sqft and rent snapshots. Two ACS 5-year vintages give income + population GROWTH; falling vacancy is a
// bonus. Returns null for a ZIP we have no data on — never invents a trajectory. Every number is real
// public data; the composite score is a transparent, labeled blend, not a black box.

import acs from "./data/zip-acs.json";

export interface AcsZip {
  income?: number | null; // latest median household income
  pop?: number | null; // latest population
  vacancyPct?: number | null; // latest residential vacancy %
  incomeGrowthPct?: number | null; // vs the prior vintage
  popGrowthPct?: number | null;
  vacancyDeltaPct?: number | null; // change in vacancy (negative = improving)
}

// The committed JSON has a huge precise inferred type; cast via `unknown` to our shape.
const DATA = acs as unknown as {
  byZip?: Record<string, AcsZip>;
  baseline?: Record<string, number>;
  updated?: string;
};

const BY_ZIP: Record<string, AcsZip> = DATA.byZip || {};

// National-median baseline per metric (from the snapshot). Growth is judged RELATIVE to this — a ZIP whose
// nominal income "grew 28%" only kept pace with inflation, so absolute growth means nothing; out/under-
// performing the national median is the real signal.
const BASE: {
  incomeGrowthPct: number;
  popGrowthPct: number;
  vacancyDeltaPct: number;
} = {
  incomeGrowthPct: 0,
  popGrowthPct: 0,
  vacancyDeltaPct: 0,
  ...(DATA.baseline || {}),
};

export const ACS_UPDATED: string = DATA.updated || "";

export type Trajectory = "rising" | "stable" | "declining";

export interface NeighborhoodScore {
  score: number; // 0–100 composite
  trajectory: Trajectory;
  label: string; // human, e.g. "Rising — incomes +9%, population +3%"
  income: number | null;
  incomeGrowthPct: number | null;
  popGrowthPct: number | null;
  vacancyPct: number | null;
}

const clamp = (n: number, lo: number, hi: number) =>
  Math.max(lo, Math.min(hi, n));

/**
 * Neighborhood trajectory for a ZIP. Composite 0–100 from income growth (the strongest appreciation
 * signal), population growth, and vacancy direction — each mapped to a bounded sub-score and blended.
 * Null when the ZIP isn't in the ACS snapshot (so callers show nothing rather than a fabricated read).
 */
export function neighborhoodScore(
  zip?: string | null,
): NeighborhoodScore | null {
  const z = zip ? String(zip).trim().slice(0, 5) : "";
  const d = BY_ZIP[z];
  if (!d) return null;

  const ig = d.incomeGrowthPct ?? null;
  const pg = d.popGrowthPct ?? null;
  const vac = d.vacancyPct ?? null;
  const vd = d.vacancyDeltaPct ?? null;

  // Sub-scores, each 0–100, centered at 50 = the NATIONAL MEDIAN (not zero) so inflation-driven nominal
  // growth doesn't rate every ZIP "rising". A ZIP outperforming the median rises above 50, underperforming
  // falls below. Population is the cleanest signal (not inflation-distorted) so it's weighted like income.
  const incomeSub =
    ig == null ? 50 : clamp(50 + (ig - BASE.incomeGrowthPct) * 1.2, 0, 100);
  const popSub =
    pg == null ? 50 : clamp(50 + (pg - BASE.popGrowthPct) * 1.2, 0, 100);
  const vacSub =
    vd == null ? 50 : clamp(50 - (vd - BASE.vacancyDeltaPct) * 4, 0, 100); // falling vacancy vs baseline = better

  // Population weighted highest — it's the least inflation-distorted signal of real neighborhood demand
  // (income % off a low base can overstate a collapsing area).
  const score = Math.round(incomeSub * 0.35 + popSub * 0.45 + vacSub * 0.2);
  const trajectory: Trajectory =
    score >= 62 ? "rising" : score <= 42 ? "declining" : "stable";

  const parts: string[] = [];
  if (ig != null) {
    // Show income growth RELATIVE to the national median (raw nominal % is mostly inflation, misleading).
    const rel = Math.round(ig - BASE.incomeGrowthPct);
    parts.push(`incomes ${rel >= 0 ? "+" : ""}${rel}% vs avg`);
  }
  if (pg != null) parts.push(`population ${pg >= 0 ? "+" : ""}${pg}%`);
  const cap = trajectory[0].toUpperCase() + trajectory.slice(1);
  const label = parts.length ? `${cap} — ${parts.join(", ")}` : cap;

  return {
    score,
    trajectory,
    label,
    income: d.income ?? null,
    incomeGrowthPct: ig,
    popGrowthPct: pg,
    vacancyPct: vac,
  };
}
