export const ALL_CAR_SOURCES = [

  // ═══════════════════════════════════════════
  // SALVAGE AUCTIONS — highest margins for dealers
  // ═══════════════════════════════════════════
  {
    id: 'copart',
    name: 'Copart',
    url: 'https://www.copart.com',
    category: 'salvage',
    tier: 'S',
    reach: '125,000+ active lots, 200 yards nationwide',
    scrapeMethod: 'patchright + FlareSolverr',
    schedule: '*/5 8-18 * * 1-5',
    stateFilter: true,
    profitPotential: 'very_high',
    notes: 'Largest salvage auction. Requires Cloudflare bypass.',
    icon: '🔨',
  },
  {
    id: 'iaa',
    name: 'IAA / RB Global',
    url: 'https://www.iaai.com',
    category: 'salvage',
    tier: 'S',
    reach: '200 locations, 40k+ vehicles/week',
    scrapeMethod: 'cheerio',
    schedule: '*/30 * * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    notes: 'Second largest salvage. Cheerio works well.',
    icon: '🔨',
  },
  {
    id: 'abetter-bid',
    name: 'A Better Bid',
    url: 'https://www.abetter.bid',
    category: 'salvage',
    tier: 'A',
    reach: 'Copart proxy — public access without dealer license',
    scrapeMethod: 'cheerio',
    schedule: '*/15 * * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    notes: 'Great for non-licensed buyers accessing Copart inventory',
    icon: '🔨',
  },
  {
    id: 'autobidmaster',
    name: 'AutoBidMaster',
    url: 'https://www.autobidmaster.com',
    category: 'salvage',
    tier: 'A',
    reach: '162,000+ cars — Copart + IAA access',
    scrapeMethod: 'cheerio',
    schedule: '*/20 * * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    icon: '🔨',
  },
  {
    id: 'salvagebid',
    name: 'SalvageBid',
    url: 'https://www.salvagebid.com',
    category: 'salvage',
    tier: 'B',
    scrapeMethod: 'cheerio',
    schedule: '*/30 * * * *',
    stateFilter: true,
    profitPotential: 'high',
    icon: '🔨',
  },
  {
    id: 'globalaa',
    name: 'Global Auto Auctions',
    url: 'https://www.globalaa.com',
    category: 'salvage',
    tier: 'B',
    reach: 'No-license repo + salvage',
    scrapeMethod: 'cheerio',
    schedule: '0 */2 * * *',
    stateFilter: true,
    profitPotential: 'high',
    icon: '🔨',
  },
  {
    id: 'e2b',
    name: 'E2B Salvage',
    url: 'https://www.e2bsalvage.com',
    category: 'salvage',
    tier: 'C',
    scrapeMethod: 'cheerio',
    schedule: '0 6 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    icon: '🔨',
  },
  {
    id: 'insurance-auto',
    name: 'Insurance Auto Auctions',
    url: 'https://www.iaai.com', // same as IAA
    category: 'salvage',
    tier: 'S',
    scrapeMethod: 'cheerio',
    schedule: '*/30 * * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    icon: '🔨',
  },

  // ═══════════════════════════════════════════
  // WHOLESALE DEALER AUCTIONS
  // ═══════════════════════════════════════════
  {
    id: 'manheim',
    name: 'Manheim Express',
    url: 'https://www.manheim.com',
    category: 'wholesale',
    tier: 'S',
    reach: 'Cox — largest US wholesale, 130 locations + online',
    scrapeMethod: 'patchright',
    schedule: '*/15 * * * *',
    stateFilter: true,
    profitPotential: 'high',
    notes: 'Also provides MMR (market value data)',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'adesa',
    name: 'ADESA / BacklotCars',
    url: 'https://www.adesa.com',
    category: 'wholesale',
    tier: 'S',
    reach: 'KAR Global — 200+ US locations',
    scrapeMethod: 'patchright',
    schedule: '*/20 * * * *',
    stateFilter: true,
    profitPotential: 'high',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'acv',
    name: 'ACV Auctions',
    url: 'https://www.acvauctions.com',
    category: 'wholesale',
    tier: 'S',
    reach: 'D2D marketplace, 18,000+ dealers',
    scrapeMethod: 'patchright',
    schedule: '*/10 * * * *',
    stateFilter: true,
    profitPotential: 'high',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'openlane',
    name: 'OPENLANE',
    url: 'https://www.openlane.com',
    category: 'wholesale',
    tier: 'A',
    reach: 'KAR — off-lease, manufacturer vehicles',
    scrapeMethod: 'patchright',
    schedule: '*/20 * * * *',
    stateFilter: false,
    profitPotential: 'high',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'eblock',
    name: 'EBlock / EDealer',
    url: 'https://www.eblock.ca',
    category: 'wholesale',
    tier: 'A',
    reach: 'Live synced D2D, US + Canada',
    scrapeMethod: 'patchright',
    schedule: '*/20 * * * *',
    stateFilter: true,
    profitPotential: 'high',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'smartauction',
    name: 'SmartAuction',
    url: 'https://www.smartauctionusa.com',
    category: 'wholesale',
    tier: 'A',
    reach: 'GM-Ally off-lease vehicles',
    scrapeMethod: 'cheerio',
    schedule: '0 9 * * 1-5',
    stateFilter: false,
    profitPotential: 'high',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'traderev',
    name: 'TradeRev (KAR)',
    url: 'https://www.traderev.com',
    category: 'wholesale',
    tier: 'A',
    reach: '45-minute live auctions',
    scrapeMethod: 'patchright',
    schedule: '*/20 8-18 * * 1-5',
    stateFilter: true,
    profitPotential: 'high',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'carwave',
    name: 'CarWave',
    url: 'https://www.carwave.com',
    category: 'wholesale',
    tier: 'B',
    reach: 'Dealer-to-dealer US platform',
    scrapeMethod: 'cheerio',
    schedule: '*/30 * * * *',
    stateFilter: true,
    profitPotential: 'medium',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'edge-pipeline',
    name: 'Edge Pipeline',
    url: 'https://www.edgepipeline.com',
    category: 'wholesale',
    tier: 'B',
    reach: 'AutoNation fleet runlists',
    scrapeMethod: 'cheerio',
    schedule: '0 8 * * 1-5',
    stateFilter: false,
    profitPotential: 'high',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'carmax-wholesale',
    name: 'CarMax Wholesale',
    url: 'https://www.carmax.com',
    category: 'wholesale',
    tier: 'B',
    reach: 'CarMax B2B weekly auctions',
    scrapeMethod: 'patchright',
    schedule: '0 10 * * 1',
    stateFilter: true,
    profitPotential: 'medium',
    requiresDealerLicense: true,
    icon: '🏪',
  },
  {
    id: 'ove',
    name: 'OVE (Manheim Online)',
    url: 'https://www.ove.com',
    category: 'wholesale',
    tier: 'A',
    reach: 'Manheim online remarketing',
    scrapeMethod: 'patchright',
    schedule: '*/15 * * * *',
    stateFilter: true,
    profitPotential: 'high',
    requiresDealerLicense: true,
    icon: '🏪',
  },

  // ═══════════════════════════════════════════
  // PRIVATE & CONSUMER LISTINGS
  // ═══════════════════════════════════════════
  {
    id: 'craigslist',
    name: 'Craigslist',
    url: 'https://craigslist.org',
    category: 'private',
    tier: 'S',
    reach: '50+ US cities, 60M/mo visitors',
    scrapeMethod: 'cheerio',
    schedule: '0 * * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    notes: 'Private party — high margin potential. 50 city crawlers.',
    icon: '📋',
  },
  {
    id: 'facebook',
    name: 'Facebook Marketplace',
    url: 'https://www.facebook.com/marketplace/vehicles',
    category: 'private',
    tier: 'S',
    reach: '2B users, largest private car marketplace',
    scrapeMethod: 'camoufox',
    schedule: '0 */2 * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    notes: 'Requires Camoufox (Firefox stealth) for anti-bot bypass',
    icon: '📘',
  },
  {
    id: 'ebay-motors',
    name: 'eBay Motors',
    url: 'https://www.ebay.com/motors',
    category: 'private',
    tier: 'S',
    reach: '180M+ eBay users, nationwide',
    scrapeMethod: 'cheerio',
    schedule: '*/15 * * * *',
    stateFilter: true,
    profitPotential: 'high',
    notes: 'Auction + BIN. Best for specialty and rare vehicles.',
    icon: '🏷️',
  },
  {
    id: 'offerup',
    name: 'OfferUp',
    url: 'https://offerup.com/motors',
    category: 'private',
    tier: 'A',
    reach: '20M/mo, local cash buyers',
    scrapeMethod: 'patchright',
    schedule: '0 */2 * * *',
    stateFilter: true,
    profitPotential: 'high',
    icon: '📱',
  },
  {
    id: 'carscom',
    name: 'Cars.com',
    url: 'https://www.cars.com',
    category: 'retail',
    tier: 'S',
    reach: '25M/mo, dealer + private',
    scrapeMethod: 'cheerio',
    schedule: '0 */6 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    icon: '🚗',
  },
  {
    id: 'cargurus',
    name: 'CarGurus',
    url: 'https://www.cargurus.com',
    category: 'retail',
    tier: 'S',
    reach: '40M/mo, deal-rating system',
    scrapeMethod: 'cheerio',
    schedule: '0 */6 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    icon: '📊',
  },
  {
    id: 'autotrader',
    name: 'AutoTrader',
    url: 'https://www.autotrader.com',
    category: 'retail',
    tier: 'A',
    reach: '33M/mo, dealer focus',
    scrapeMethod: 'cheerio',
    schedule: '0 */6 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    icon: '🚙',
  },
  {
    id: 'carsforsale',
    name: 'CarsForSale.com',
    url: 'https://www.carsforsale.com',
    category: 'retail',
    tier: 'B',
    reach: 'Independent dealer focus',
    scrapeMethod: 'cheerio',
    schedule: '0 */12 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    icon: '🚗',
  },
  {
    id: 'autolist',
    name: 'Autolist',
    url: 'https://www.autolist.com',
    category: 'retail',
    tier: 'B',
    reach: 'Aggregator, real listings from multiple sources',
    scrapeMethod: 'cheerio',
    schedule: '0 */12 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    icon: '📋',
  },
  {
    id: 'autotempest',
    name: 'AutoTempest',
    url: 'https://www.autotempest.com',
    category: 'aggregator',
    tier: 'A',
    reach: 'Aggregates Cars.com, Carvana, TrueCar, eBay, Craigslist',
    scrapeMethod: 'cheerio',
    schedule: '0 */4 * * *',
    stateFilter: true,
    profitPotential: 'high',
    notes: 'One scrape hits multiple platforms. Efficiency win.',
    icon: '🔍',
  },
  {
    id: 'carvana',
    name: 'Carvana',
    url: 'https://www.carvana.com',
    category: 'retail',
    tier: 'B',
    reach: '100k+ vehicles, nationwide delivery',
    scrapeMethod: 'patchright',
    schedule: '0 */12 * * *',
    stateFilter: false,
    profitPotential: 'low',
    notes: 'High retail pricing. Good as pricing benchmark.',
    icon: '🚗',
  },
  {
    id: 'vroom',
    name: 'Vroom',
    url: 'https://www.vroom.com',
    category: 'retail',
    tier: 'C',
    scrapeMethod: 'cheerio',
    schedule: '0 */12 * * *',
    stateFilter: false,
    profitPotential: 'low',
    notes: 'Pricing benchmark only',
    icon: '🚗',
  },
  {
    id: 'carmax',
    name: 'CarMax (retail)',
    url: 'https://www.carmax.com',
    category: 'retail',
    tier: 'B',
    reach: '220+ stores, no-haggle pricing',
    scrapeMethod: 'patchright',
    schedule: '0 */12 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    notes: 'Good pricing benchmark for comparable makes/models',
    icon: '🚗',
  },
  {
    id: 'truecar',
    name: 'TrueCar',
    url: 'https://www.truecar.com',
    category: 'retail',
    tier: 'C',
    scrapeMethod: 'cheerio',
    schedule: '0 */12 * * *',
    stateFilter: true,
    profitPotential: 'low',
    notes: 'Certified dealer pricing — good market value reference',
    icon: '🚗',
  },
  {
    id: 'autobytel',
    name: 'Autobytel / Autobytel.com',
    url: 'https://www.autobytel.com',
    category: 'retail',
    tier: 'C',
    scrapeMethod: 'cheerio',
    schedule: '0 0 * * *',
    stateFilter: true,
    profitPotential: 'low',
    icon: '🚗',
  },
  {
    id: 'cars-and-bids',
    name: 'Cars & Bids',
    url: 'https://carsandbids.com',
    category: 'auction',
    tier: 'B',
    reach: 'Modern enthusiast cars (post-1980)',
    scrapeMethod: 'cheerio',
    schedule: '0 */6 * * *',
    stateFilter: false,
    profitPotential: 'high',
    notes: 'Good for finding undervalued modern performance cars',
    icon: '🏁',
  },
  {
    id: 'motorious',
    name: 'Motorious',
    url: 'https://www.motorious.com',
    category: 'auction',
    tier: 'C',
    scrapeMethod: 'cheerio',
    schedule: '0 0 * * *',
    stateFilter: false,
    profitPotential: 'medium',
    icon: '🏁',
  },

  // ═══════════════════════════════════════════
  // GOVERNMENT, REPO & FLEET
  // ═══════════════════════════════════════════
  {
    id: 'gsa-auctions',
    name: 'GSA Auctions',
    url: 'https://gsaauctions.gov',
    category: 'government',
    tier: 'A',
    reach: 'Federal surplus vehicles — underpriced',
    scrapeMethod: 'cheerio',
    schedule: '0 6 * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    notes: 'Fleet trucks, SUVs, law enforcement vehicles at below-market prices',
    icon: '🏛️',
  },
  {
    id: 'public-surplus',
    name: 'Public Surplus',
    url: 'https://www.publicsurplus.com',
    category: 'government',
    tier: 'A',
    reach: 'Municipal + county + state surplus vehicles',
    scrapeMethod: 'cheerio',
    schedule: '0 6 * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    icon: '🏛️',
  },
  {
    id: 'govplanet',
    name: 'GovPlanet',
    url: 'https://www.govplanet.com',
    category: 'government',
    tier: 'B',
    reach: 'Heavy equipment + fleet',
    scrapeMethod: 'cheerio',
    schedule: '0 6 * * *',
    stateFilter: true,
    profitPotential: 'high',
    icon: '🏛️',
  },
  {
    id: 'policeauctions',
    name: 'PoliceAuctions.com',
    url: 'https://www.policeauctions.com',
    category: 'government',
    tier: 'B',
    reach: 'Law enforcement seizures',
    scrapeMethod: 'cheerio',
    schedule: '0 7 * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    icon: '🚔',
  },
  {
    id: 'propertyroom',
    name: 'PropertyRoom.com',
    url: 'https://www.propertyroom.com',
    category: 'government',
    tier: 'B',
    reach: 'Police + government surplus, eBay partner',
    scrapeMethod: 'cheerio',
    schedule: '0 7 * * *',
    stateFilter: true,
    profitPotential: 'high',
    icon: '🚔',
  },
  {
    id: 'repocom',
    name: 'Repo.com',
    url: 'https://www.repo.com',
    category: 'repo',
    tier: 'B',
    reach: 'Bank & credit union repossessions',
    scrapeMethod: 'cheerio',
    schedule: '0 7 * * 1-5',
    stateFilter: true,
    profitPotential: 'very_high',
    icon: '🏦',
  },
  {
    id: 'ibidauto',
    name: 'iBid Auto',
    url: 'https://www.ibidauto.com',
    category: 'repo',
    tier: 'B',
    reach: 'Bank repo network auctions',
    scrapeMethod: 'cheerio',
    schedule: '0 7 * * 1-5',
    stateFilter: true,
    profitPotential: 'high',
    icon: '🏦',
  },
  {
    id: 'seized-cars',
    name: 'SeizedCars.com',
    url: 'https://www.seizedcars.com',
    category: 'government',
    tier: 'C',
    scrapeMethod: 'cheerio',
    schedule: '0 8 * * *',
    stateFilter: true,
    profitPotential: 'high',
    icon: '🚔',
  },

  // ═══════════════════════════════════════════
  // COLLECTOR & SPECIALTY
  // ═══════════════════════════════════════════
  {
    id: 'bring-a-trailer',
    name: 'Bring a Trailer',
    url: 'https://bringatrailer.com',
    category: 'collector',
    tier: 'A',
    reach: 'Premium collector cars, 250k+ community',
    scrapeMethod: 'cheerio',
    schedule: '0 2 * * *',
    stateFilter: false,
    profitPotential: 'high',
    notes: 'Sellers pay $99. Buyers pay nothing. Good for specialty.',
    icon: '🏆',
  },
  {
    id: 'hemmings',
    name: 'Hemmings',
    url: 'https://www.hemmings.com',
    category: 'collector',
    tier: 'B',
    reach: 'Classic + antique + muscle cars, print + digital',
    scrapeMethod: 'cheerio',
    schedule: '0 2 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    icon: '🏆',
  },
  {
    id: 'classiccars',
    name: 'ClassicCars.com',
    url: 'https://classiccars.com',
    category: 'collector',
    tier: 'B',
    scrapeMethod: 'cheerio',
    schedule: '0 2 * * *',
    stateFilter: true,
    profitPotential: 'medium',
    icon: '🏆',
  },
  {
    id: 'dupont-registry',
    name: 'DuPont Registry',
    url: 'https://www.dupontregistry.com',
    category: 'collector',
    tier: 'C',
    reach: 'Luxury + exotic vehicles',
    scrapeMethod: 'cheerio',
    schedule: '0 2 * * *',
    stateFilter: false,
    profitPotential: 'medium',
    icon: '💎',
  },
  {
    id: 'mecum',
    name: 'Mecum Auctions',
    url: 'https://www.mecum.com',
    category: 'collector',
    tier: 'B',
    reach: 'Large collector car events, 10k+ vehicles/year',
    scrapeMethod: 'cheerio',
    schedule: '0 0 * * *',
    stateFilter: false,
    profitPotential: 'high',
    icon: '🏆',
  },
  {
    id: 'barrett-jackson',
    name: 'Barrett-Jackson',
    url: 'https://www.barrett-jackson.com',
    category: 'collector',
    tier: 'C',
    reach: 'Premium collector auctions (Scottsdale, Palm Beach, Las Vegas)',
    scrapeMethod: 'cheerio',
    schedule: '0 0 * * *',
    stateFilter: false,
    profitPotential: 'high',
    icon: '🏆',
  },

  // ═══════════════════════════════════════════
  // INDEPENDENT DEALER SITES (847+ discovered)
  // ═══════════════════════════════════════════
  {
    id: 'indi-dealers',
    name: 'Independent Dealer Sites (847+)',
    url: 'multiple',
    category: 'independent',
    tier: 'A',
    reach: 'AE Miami 74, 111 Auto Resale, STL Pipeline + 844 more',
    scrapeMethod: 'cheerio + patchright for Cloudflare-protected',
    schedule: '0 2 * * *',
    stateFilter: true,
    profitPotential: 'very_high',
    notes: 'Highest margins. Dealers often price below market. Scraped 2am nightly.',
    icon: '🏠',
  },
];

// Helper: get sources by state (for dealer location filtering)
export function getSourcesByState(state: string) {
  return ALL_CAR_SOURCES.filter(s => s.stateFilter || !s.stateFilter);
}

// Helper: get sources by category
export function getSourcesByCategory(cat: string) {
  return ALL_CAR_SOURCES.filter(s => s.category === cat);
}

// Stats
export const SOURCE_STATS = {
  total: ALL_CAR_SOURCES.length,
  byCategory: {
    salvage: ALL_CAR_SOURCES.filter(s => s.category === 'salvage').length,
    wholesale: ALL_CAR_SOURCES.filter(s => s.category === 'wholesale').length,
    private: ALL_CAR_SOURCES.filter(s => s.category === 'private').length,
    retail: ALL_CAR_SOURCES.filter(s => s.category === 'retail').length,
    government: ALL_CAR_SOURCES.filter(s => s.category === 'government').length,
    repo: ALL_CAR_SOURCES.filter(s => s.category === 'repo').length,
    collector: ALL_CAR_SOURCES.filter(s => s.category === 'collector').length,
    independent: 847,
  },
};
