export const LISTING_PLATFORMS = [
  {
    id: 'facebook',
    name: 'Facebook Marketplace',
    cost: 0,
    costLabel: 'Free',
    reach: '2B users',
    bestFor: 'Local buyers, fast response',
    method: 'manual',
    priority: 1,
  },
  {
    id: 'craigslist',
    name: 'Craigslist',
    cost: 5,
    costLabel: '$5/post',
    reach: '60M/mo',
    bestFor: 'Budget buyers, local cash deals',
    method: 'bulk_api',
    priority: 2,
  },
  {
    id: 'carscom',
    name: 'Cars.com',
    cost: 0,
    costLabel: 'Free',
    reach: '25M/mo',
    bestFor: 'In-market buyers',
    method: 'feed',
    priority: 3,
  },
  {
    id: 'cargurus',
    name: 'CarGurus',
    cost: 250,
    costLabel: '$250/mo',
    reach: '40M/mo',
    bestFor: 'Deal-rating system drives qualified leads',
    method: 'feed',
    priority: 4,
  },
  {
    id: 'ebay',
    name: 'eBay Motors',
    cost: 60,
    costLabel: '$60/mo dealer sub',
    reach: '180M users',
    bestFor: 'National reach, trucks + specialty',
    method: 'api',
    priority: 5,
  },
]

export const DAMAGE_TYPES = [
  { value: 'clean', label: 'Clean / No Damage', repair: 0 },
  { value: 'minor_scratch', label: 'Minor Scratch / Ding', repair: 400 },
  { value: 'hail', label: 'Hail Damage', repair: 1200 },
  { value: 'minor_collision', label: 'Minor Collision', repair: 2500 },
  { value: 'rear_end', label: 'Rear End', repair: 3200 },
  { value: 'front_end', label: 'Front End', repair: 4500 },
  { value: 'side_damage', label: 'Side Damage', repair: 3800 },
  { value: 'mechanical', label: 'Mechanical', repair: 5500 },
  { value: 'flood', label: 'Flood', repair: 8000 },
  { value: 'fire', label: 'Fire', repair: 12000 },
  { value: 'frame', label: 'Frame Damage', repair: 15000 },
  { value: 'salvage', label: 'Salvage / Rebuilt', repair: 7000 },
  { value: 'total_loss', label: 'Total Loss', repair: 20000 },
  { value: 'parts_only', label: 'Parts Only', repair: 0 },
  { value: 'major_collision', label: 'Major Collision', repair: 8500 },
  { value: 'suspension', label: 'Suspension / Axle', repair: 6000 },
]

export const PLAN_TIERS = [
  { id: 'scout', name: 'Scout', price: 49, description: '50 scans/day, 1 alert' },
  { id: 'pro', name: 'Pro', price: 149, description: 'Unlimited scans, fleet + listing blast' },
  { id: 'elite', name: 'Elite', price: 349, description: 'Outreach, API, unlimited alerts' },
]
